"""
Django settings for sistema_encomendas project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import pymysql # Ensure pymysql is imported if using MySQL

# Activate MySQL driver
pymysql.install_as_MySQLdb()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-u+=oong8ajl(w-6f8&=-f+bw_jkd^u^0fs!7a)@kk&nx&vo&^8' # Replace with your actual key

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [] # Add '127.0.0.1', 'localhost' for development if needed


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'encomendas', # Seu app
    # Adicionados para a API:
    'rest_framework',
    'rest_framework_simplejwt',
    'corsheaders',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    # Adicionado CORS Middleware aqui:
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


# Configuração do REST Framework
REST_FRAMEWORK = {
    # Define a autenticação padrão como JWT (JSON Web Tokens)
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    # Define que, por padrão, todas as views da API exigirão autenticação
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    # (Opcional) Configura paginação padrão para listas da API
    # 'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    # 'PAGE_SIZE': 20
}

# Configuração do CORS (Cross-Origin Resource Sharing)
# Permite que seu frontend (rodando em outra porta/domínio) acesse a API
CORS_ALLOWED_ORIGINS = [
    # Endereço do seu app React em desenvolvimento (ajuste a porta se necessário)
    "http://localhost:5173",   # <--- ADICIONE ESTA LINHA
    "http://127.0.0.1:5173",  # <--- ADICIONE ESTA LINHA (boa prática incluir ambos)
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    # Em produção, adicione o domínio do seu frontend:
    # "https://seu-dominio-frontend.com",
]
# (Opcional) Se precisar permitir que o frontend envie cookies (como CSRF ou session)
# CORS_ALLOW_CREDENTIALS = True
# (Opcional, mas comum) Permite métodos HTTP específicos
# CORS_ALLOW_METHODS = [
#     "DELETE",
#     "GET",
#     "OPTIONS",
#     "PATCH",
#     "POST",
#     "PUT",
# ]
# (Opcional, mas comum) Permite cabeçalhos específicos
# CORS_ALLOW_HEADERS = [
#     "accept",
#     "authorization",
#     "content-type",
#     "origin",
#     "x-csrftoken",
#     "x-requested-with",
# ]

# (Opcional, mas recomendado para JWT) Defina o tempo de vida dos tokens
from datetime import timedelta

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=60), # Ex: Token de acesso dura 1 hora
    "REFRESH_TOKEN_LIFETIME": timedelta(days=1),    # Ex: Token de refresh dura 1 dia
    "ROTATE_REFRESH_TOKENS": False,
    "BLACKLIST_AFTER_ROTATION": False,
    "UPDATE_LAST_LOGIN": False,

    "ALGORITHM": "HS256",
    "SIGNING_KEY": SECRET_KEY, # Reutiliza a SECRET_KEY do Django
    "VERIFYING_KEY": "",
    "AUDIENCE": None,
    "ISSUER": None,
    "JSON_ENCODER": None,
    "JWK_URL": None,
    "LEEWAY": 0,

    "AUTH_HEADER_TYPES": ("Bearer",),
    "AUTH_HEADER_NAME": "HTTP_AUTHORIZATION",
    "USER_ID_FIELD": "id",
    "USER_ID_CLAIM": "user_id",
    "USER_AUTHENTICATION_RULE": "rest_framework_simplejwt.authentication.default_user_authentication_rule",

    "AUTH_TOKEN_CLASSES": ("rest_framework_simplejwt.tokens.AccessToken",),
    "TOKEN_TYPE_CLAIM": "token_type",
    "TOKEN_USER_CLASS": "rest_framework_simplejwt.models.TokenUser",

    "JTI_CLAIM": "jti",

    "SLIDING_TOKEN_REFRESH_EXP_CLAIM": "refresh_exp",
    "SLIDING_TOKEN_LIFETIME": timedelta(minutes=5),
    "SLIDING_TOKEN_REFRESH_LIFETIME": timedelta(days=1),

    # (Opcional) Adicione mais claims ao payload do token se precisar
    # "CLAIMS_NAMESPACE": None,
}




ROOT_URLCONF = 'sistema_encomendas.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [], # Add global template directories if you have any
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'sistema_encomendas.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'sistema_encomendas',
        'USER': 'root',  # Replace with your MySQL user if different
        'PASSWORD': 'root',  # Replace with your MySQL password
        'HOST': 'localhost', # Or the IP address of your DB server
        'PORT': '3306',  # Default MySQL port
        'OPTIONS': {
            'charset': 'utf8mb4',
            # Ensure MySQL uses transactions correctly
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'pt-br'

TIME_ZONE = 'America/Sao_Paulo'

USE_I18N = True

USE_TZ = True # Important for timezone-aware datetimes


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
# Add STATIC_ROOT for collectstatic in production
# STATIC_ROOT = BASE_DIR / 'staticfiles'
# Add STATICFILES_DIRS if you have static files outside app directories
# STATICFILES_DIRS = [BASE_DIR / 'static']

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Custom User Model
AUTH_USER_MODEL = 'encomendas.Usuario'

# Authentication URLs
LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'root_redirect' # <<<--- CORRECTED VALUE
LOGOUT_REDIRECT_URL = 'login'

# Email Settings (for password reset, etc.)
# Use console backend for development to see emails in the terminal
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
# Use SMTP backend for production (replace with your actual provider details)
# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_HOST = 'smtp.example.com'
# EMAIL_PORT = 587
# EMAIL_USE_TLS = True
# EMAIL_HOST_USER = 'your-email@example.com'
# EMAIL_HOST_PASSWORD = 'your-email-password-or-app-password'
# DEFAULT_FROM_EMAIL = 'webmaster@example.com' # Email shown as sender

# Base URL for constructing absolute URLs in emails (password reset links)
# Replace with your actual domain in production
SITE_URL = 'http://127.0.0.1:8000'

# Session Settings (optional, example for longer session)
# SESSION_COOKIE_AGE = 60 * 60 * 24 * 7 * 2 # 2 weeks in seconds

# Message Framework Tags (optional, aligns with Bootstrap alert classes)
from django.contrib.messages import constants as messages
MESSAGE_TAGS = {
    messages.DEBUG: 'secondary',
    messages.INFO: 'info',
    messages.SUCCESS: 'success',
    messages.WARNING: 'warning',
    messages.ERROR: 'danger',
}

# Invitation expiration days (optional custom setting)
CONVITE_EXPIRACAO_DIAS = 7