# Generated by Django 4.2.25 on 2025-10-22 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('encomendas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='equipe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clientes', to='encomendas.equipe', verbose_name='Equipe'),
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='equipe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fornecedores', to='encomendas.equipe', verbose_name='Equipe'),
        ),
        migrations.AddField(
            model_name='produto',
            name='equipe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='produtos', to='encomendas.equipe', verbose_name='Equipe'),
        ),
        migrations.AlterField(
            model_name='encomenda',
            name='equipe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='encomendas', to='encomendas.equipe', verbose_name='Equipe Responsável'),
        ),
    ]
